# Generated by Django 3.1.2 on 2020-10-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201013_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike_type',
            options={'verbose_name_plural': 'Bike Type'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'Condition'},
        ),
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name_plural': 'Deals'},
        ),
    ]
