# Generated by Django 3.1.2 on 2020-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201014_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
