# Generated by Django 3.1.2 on 2020-10-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='models',
            new_name='comment',
        ),
    ]
