# Generated by Django 3.1.2 on 2020-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201030_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
