# Generated by Django 3.1.2 on 2020-10-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': 'Product Review'},
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='product_review',
            new_name='product',
        ),
    ]
